### ISSUE TITLE
Clean up iPad scaling

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-mobile#101]
![screen shot 2018-05-16 at 5 31 41 pm](https://user-images.githubusercontent.com/370259/40150578-46323b02-592f-11e8-9c18-0e55594127ea.png)

**Comment by carsonfarmer** [comment]
https://stackoverflow.com/questions/30269014/react-native-unwanted-black-border-on-ipad-2-simulation

**Comment by asutula** [comment]
The app is currently designed for and configured to run only on iPhone. The attached image is what happens if you install an iPhone only app on an iPad, and is normal. If we want to support iPad specifically, let's start a new discussion about how exactly to tackle that.
