### ISSUE TITLE
Fix RCTFatalException: Unhandled JS Exception: Invariant Violation: Objects are not valid as a React child (found: object with keys {domain, message, code}).

This error is located at:
    in RCTText
    in Text
    in RCTView
    in n
    in RCTView
    in e
    in RCTView
    in a
    in Connect(a)
    in t
    in RCTView
    in n
    in t
    in n
    in RCTView
    in RCTView
    in t
    in RCTView
    in e
    in r
    in Unknown
    in n
    in n
    in t
    in RCTView
    in n
    in t
    in n
    in RCTView
    in RCTView
    in t
    in RCTView
    in e
    in r
    in Unknown
    in n
    in n
    in t
    in t
    in withCachedChildNavigation(t)
    in Unknown
    in n
    in n
    in RCTView
    in t
    in Connect(t)
    in e
    in n
    in t
    in RCTView
    in RCTView
    in t in ReactNativeRenderer-prod.js line 2694

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-mobile#11]
### Reason ###

RCTFatalException: Unhandled JS Exception: Invariant Violation: Objects are not valid as a React child (found: object with keys {domain, message, code}).

This error is located at:
    in RCTText
    in Text
    in RCTView
    in n
    in RCTView
    in e
    in RCTView
    in a
    in Connect(a)
    in t
    in RCTView
    in n
    in t
    in n
    in RCTView
    in RCTView
    in t
    in RCTView
    in e
    in r
    in Unknown
    in n
    in n
    in t
    in RCTView
    in n
    in t
    in n
    in RCTView
    in RCTView
    in t
    in RCTView
    in e
    in r
    in Unknown
    in n
    in n
    in t
    in t
    in withCachedChildNavigation(t)
    in Unknown
    in n
    in n
    in RCTView
    in t
    in Connect(t)
    in e
    in n
    in t
    in RCTView
    in RCTView
    in t

### Link to App Center ###

* [https://appcenter.ms/users/andrewxhill/apps/Textile-Photos/crashes/groups/63acd00cc4c9cc1574870e21ead1630e5166535c](https://appcenter.ms/users/andrewxhill/apps/Textile-Photos/crashes/groups/63acd00cc4c9cc1574870e21ead1630e5166535c)

**Comment by asutula** [comment]
Looks like it's trying to render an error object to the UI instead of an error message string. @andrewxhill @sanderpick @carsonfarmer do any of you remember using the app when it crashed after this recent build? What were you doing when it crashed?

**Comment by asutula** [comment]
The only place i can think of that we try to display the error text is when you tap on the '!' symbol for a failed image add

**Comment by andrewxhill** [comment]
oh, yeah, duh. i've been triggering this. if an image has an exclamation point now and you click on it the app crashes.

**Comment by asutula** [comment]
Ok I'm 99% sure this is a data lack-of-migration issue. You were running a previously running a version that was incorrectly storing an error object instead of the error message. This has been fixed already, but you either need to do a fresh install or stop tapping those old error icons ;)

**Comment by andrewxhill** [comment]
haha, kk
