### ISSUE TITLE
Stub out framework for Jest-based tests

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-mobile#114]
Its time to start formal unit/integration testing. React Native provides pretty good Jest-based testing facilities, including auto-mocking modules etc. There are also [some examples](https://stackoverflow.com/questions/41339996/how-to-test-a-react-native-component-that-imports-a-custom-native-module-with-je) for mocking custom NativeModules.

**Comment by andrewxhill** [comment]
fixed in #167

**Comment by carsonfarmer** [comment]
Not sure why this isn't closed?
