### ISSUE TITLE
'undefined' node state when returning from sleep

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#118]
If the node is shutdown from an actual background event triggered by the user, all is well. Probably related to https://github.com/textileio/textile-mobile/issues/107, stemming from a background event possibly not being triggered when the app is left to close itself via the screen auto-dimming

**Comment by asutula** [comment]
Yea, this should be in better shape once #119 is merged. There was also an issue in `textile-go` where the node would fail to start every other time we tried to start it. @andrewxhill fixed that, so that should help too.

**Comment by sanderpick** [comment]
Okay awesome. The start / stop was related to the public thread update, right?

**Comment by asutula** [comment]
Yes

**Comment by sanderpick** [comment]
steps to reproduce:
1) run on device from xcode
2) hit stop so the debugger disconnects
3) reopen app
4) just let it sit there until the screen shuts off
5) unlock phone
5) tap a thumb, for me it’s “connecting…” forever, which is think is the same seeing "undefined" node state in older builds

**Comment by sanderpick** [comment]
fixed
