### ISSUE TITLE
Images left in repo after upload

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#133]
Would be useful if others can confirm this on their own repos.

![screenshot 2018-05-29 16 41 33](https://user-images.githubusercontent.com/361000/40789951-85590386-64a8-11e8-8971-7268de633663.png)

**Comment by asutula** [comment]
Testing on the sim first... Seems to be working fine.

**Comment by sanderpick** [comment]
Great. I've since looked at device logs from a fresh install (that added photos), and the dir is empty.

**Comment by asutula** [comment]
That's good. My theory is that our call to the Go layer's `addPhoto` was failing for you for some period of time. The way our code is currently structured, that would result in the photos hanging around:
```
try {
  ...
  const multipartData = yield call(IPFS.addImageAtPath, photo.path, photo.thumbPath, 'default')
  yield call(RNFS.unlink, photo.path)
  yield call(RNFS.unlink, photo.thumbPath)
} catch { ... }
```
That code is inside of a `try/catch`. You can see if the call to `addPhotos` fails, the following `unlink` calls never run. In @andrewxhill's latest branch that improves photo querying, he handles this better with the `unlink` calls in a `finally` clause.

**Comment by andrewxhill** [comment]
i fixed that though... i think

**Comment by asutula** [comment]
Yes, that's what i said ;)
