### ISSUE TITLE
Signup broken

### ISSUE THREAD

**Issue by asutula** [textileio/textile-mobile#158]
After latest update to Go layer, all the wires aren't connected correctly. Working on the update now.

WIP in #160

**Comment by sanderpick** [comment]
dang, the one thing I didn't test :) although the go API didn't change. I must have messed up the bridge?

**Comment by asutula** [comment]
Yea you can see the updates i'm making here:
https://github.com/textileio/textile-mobile/pull/160/files#diff-31194fb85255ee9075724a56ebd48584L35
and:
https://github.com/textileio/textile-mobile/pull/160/files#diff-31194fb85255ee9075724a56ebd48584L35

Similar issue with login. Just inconsistencies from ObjC/Java to the JS module to it's use.

**Comment by sanderpick** [comment]
huh, i don't think I changed anything besides the name of the signup method in any of the layers. those are the same line, no?

**Comment by asutula** [comment]
It's just that sign up and log in don't return anything from the go layer, but the code using the API was trying to parse a token or error out of a return value that didn't exist. Guess it was working because we weren't actually doing anything with the return value.

**Comment by sanderpick** [comment]
ahh, makes sense. good eye!
