### ISSUE TITLE
ProgressiveImage extra loading

### ISSUE THREAD

**Issue by asutula** [textileio/textile-mobile#164]
I'm seeing an extra image load from the Node in the `ProgressiveImage` component. It seems that the `TextileImage` that loads the thumb switches it's 'path' prop from `thumb` to `photo`. I don't think that's necessary because there's a separate `TextileImage` that loads the `photo` path.

**Comment by andrewxhill** [comment]
shouldn't be like that from what i know. could this have been from that lingering asyncimage i removed last week?

**Comment by asutula** [comment]
My theory is that there is a brief moment after the path to load in the component state is changed from `thumb` to `photo`, but before the thumb `TextileImage` is removed from the `ProgressiveImage` view hierarchy. So this would cause the `TextileImage` that was used for the thumb to load the full res photo. If this is the case, we should just not share the `path` state between both `TextileImage`s in `ProgressiveImage`.

**Comment by asutula** [comment]
My theory is that there is a brief moment after the path to load in the component state is changed from `thumb` to `photo`, but before the thumb `TextileImage` is removed from the `ProgressiveImage` view hierarchy. So this would cause the `TextileImage` that was used for the thumb to load the full res photo. If this is the case, we should just not share the `path` state between both `TextileImage`s in `ProgressiveImage`.
