### ISSUE TITLE
Duplicate / out of order photos added

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#171]
@andrewxhill had some ideas on why this is happening, but wanted to log... opened the app, got a few new photos but one of them is from a couple weeks ago.

**Comment by sanderpick** [comment]
(... and had already been added)

**Comment by andrewxhill** [comment]
This should not happen since #174, reopen if you see again. Aaron reported something yesterday but I think it was a (non) migration from pre 174...
