### ISSUE TITLE
Lost connection to background transfer service

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#172]
@asutula I think you had some update on this, but I can't remember what it was and didn't see an issue for it. Still seeing them from time to time.

**Comment by asutula** [comment]
I wasn't able to figure anything out, but we do have retries in there now, that should help. May need to put some more work into the retry logic.

**Comment by sanderpick** [comment]
havent seen this for awhile... prob related to the non-file based uploaders
