### ISSUE TITLE
Wait for pairing confirmation before confirming that the devices are paired

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-mobile#177]
Currently in DevicesRedux, the state 'added' is reached as soon as the device is added to the wallet. But we need a step after this where the device is confirmed as being paired, this is later confirmed by a message from the external device saying it received the pair.

**Comment by sanderpick** [comment]
I believe calling pair will either fail or succeed... as in, it's sync. We should expose the ability to _not_ fallback to offline message sending and do that here.

**Comment by andrewxhill** [comment]
ahhh gotcha
