### ISSUE TITLE
Add Thread invite link to a native share dialog

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-mobile#179]
Just thinking this through. Seems like we want,

- [ ] a share link in every non-default thread
- [ ] clicking the link will grab the URL from textile-go
- [ ] toss the payload into the native share method and open it for the user

Later on we talked about adding a block to the Thread saying that a public invite was created, we can do that later.

**Comment by andrewxhill** [comment]
Giving this to you aaron, seems like the last piece actually remaining to have a little internal test of this tomorrow / tuesday. was going to just hack it in on top of my branch but not sure where that share dialog trigger / construction should live currently. should be quick either way, so let me know if you want me to just do it

**Comment by asutula** [comment]
Sounds good to me.

**Comment by andrewxhill** [comment]
done
