### ISSUE TITLE
Store Mnemonic so that it can be shown to user at later date

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-mobile#190]

**Comment by asutula** [comment]
This seems important since it's something we can't retroactively get for the user.

**Comment by asutula** [comment]
@sanderpick how do we get the mnemonic anyway? Not clear to me.

**Comment by asutula** [comment]
I see there' a `mnemonic` property on the node that returns a string, but if we can just fetch it from there any time, why do we need to store it as this ticket describes?

**Comment by sanderpick** [comment]
It's not persisted. It will be an empty string unless the repo (specifically peer keys) was actually created (fist run only)

**Comment by sanderpick** [comment]
ideally I'd pass back three things from the mobile version of NewNode: the node, the mnemonic, and an error. however, gobind will only let us pass back two things.

**Comment by sanderpick** [comment]
(that's why the mnemonic prop is on the mobile wrapper)

**Comment by asutula** [comment]
Ok, so i can query that property right after the node is created and store it, cool.

**Comment by asutula** [comment]
At what point is the mnemonic available? Right after the node is created? or started?
