### ISSUE TITLE
Use the name 'cameraroll' for default thread 

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-mobile#198]
not that we need to say it in the UI really, but for the case of pairing with desktop it will be helpful

**Comment by andrewxhill** [comment]
Noticing a bit of logic around the name of the thread. E.g. don't show sharing UI if the thread is named default. I think we might want to just throw a flag on the thread object 'private':bool. This would allow a user to rename their 'cameraroll' in the future without any consequence. Also an ability to have other private threads (e.g. desktop).

**Comment by asutula** [comment]
This is done. Not currently showing this thread in the UI, but will after we re-enable camera roll sync
