### ISSUE TITLE
Cancel out of signup / signin

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#280]
Once you're in the flow, not possible to exit, correct?

**Comment by asutula** [comment]
You can switch back and forth between sign in and sign up. Not sure why you'd need to go back to the onboarding screens.

But in general, the onbaording > sign up/in > permissions > profile photo is one big static flow. We need to break it up and give ourselves flows for things like logging out and back in, just updating you profile photo, etc

**Comment by sanderpick** [comment]
Hmm, okay... I didn't see any links to go into sign in from sign up, so killed and restarted. Maybe blind?

**Comment by sanderpick** [comment]
Possible that the keyboard would not exit, so i couldn't scroll down to see the footer. Is that where the links are?

**Comment by asutula** [comment]
yea they're in the footer. You can dismiss the kb by tapping outside of the text inputs. Also maybe with the kb return key, can't remember.
