### ISSUE TITLE
Display signup / signin errors

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#281]
Tried signing up with Kesa's username, account already existed but did not get any feedback saying that

**Comment by asutula** [comment]
Strange, we do display whatever error comes back from the go layer.

**Comment by sanderpick** [comment]
K, where are they shown in the UI so I can double check?

**Comment by asutula** [comment]
Would be in a blue box at the bottom of the form. Guess there's a chance that some work got lost in the rush of merges. Let me know.

**Comment by asutula** [comment]
<img width="544" alt="screen shot 2018-07-31 at 12 52 00" src="https://user-images.githubusercontent.com/528969/43477370-9d3825a2-94c0-11e8-900b-fc96190c36e2.png">
Like this. This is the latest master.

**Comment by sanderpick** [comment]
ok, awesome. i must be loosing it... sorry for the noise
