### ISSUE TITLE
Create new RN type for remote username string

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-mobile#336]
Currently going to store username on the block but ideally it would be a remote object like profile pictures... it would work well to have a new type similar to TextileImage that handles this remote (fall back to local) lookup

**Comment by asutula** [comment]
This sounds more like an API client to me. Like we need to write an http client that can fetch whatever data from whatever url path. The fact that some username string you fetch is displayed in a text label in the app is something we can handle just like every app that fetches and displays data over http.

**Comment by sanderpick** [comment]
Ah yeah, makes sense! I was thinking a component might let the OS make the requests on a background thread (cause there will be a lot) but I guess RN uses the OS at then end of the day for network fetching

**Comment by sanderpick** [comment]
going to close this, happy with the current solution
