### ISSUE TITLE
Use full screen width for feed photos

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#337]
Going back and forth between Textile and IG, you really start to appreciate their feed layout... photos are nice to look at, may as well use all the real estate.

**Comment by andrewxhill** [comment]
just wrote SB about this this morning... getting rid of the date column

**Comment by asutula** [comment]
Yea @andrewxhill and I were talking about that yesterday. Same page.

**Comment by andrewxhill** [comment]
👯‍♂️ 🕺 🎉

**Comment by sanderpick** [comment]
sweet!

**Comment by andrewxhill** [comment]
fixed
