### ISSUE TITLE
Enabling Background Location doesn't change enable button state.

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-mobile#368]
The button state remains blue with 'enable' text. This should be updated to reflect that Background Location has been 'enabled'.

**Comment by carsonfarmer** [comment]
It seems the button styles and text are 'hard coded', but they could be updated to reflect the underlying permissions state here:
https://github.com/textileio/textile-mobile/blob/master/App/SB/views/Settings/index.js#L118

**Comment by andrewxhill** [comment]
the problem here was that we just don't have any persisted state to let us know it's been enabled long term

**Comment by carsonfarmer** [comment]
ah bummer, ok. without that, this is likely slightly confusing for a user, because its not clear that location permissions have been enabled or not. any chance we can add persistence here, or query the os on page load?

**Comment by asutula** [comment]
we should be able to query OS apis to get this state and update the UI accordingly

**Comment by andrewxhill** [comment]
it's more than OS permission though, it's a setting. disable or enable background updates via location. the OS is just whether they have granted permisssion

**Comment by carsonfarmer** [comment]
Should we close this with "won't fix" for now?
