### ISSUE TITLE
Devices screen

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#372]
List paired devices, allow removal

**Comment by sanderpick** [comment]
@asutula @andrewxhill feel like we need to bump this up to critical since we're getting a bunch of users now trying to pair w/ desktop. The api is there, `Devices` will list your devices, `RemoveDevice(id string)` will remove by `id`.

**Comment by asutula** [comment]
No longer device related APIs available, and I think how we'd manage multiple devices has fundamentally changes. Closing and we can re-open or create new when this becomes a topic of discussion again.
