### ISSUE TITLE
Layout suggested tweaks

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#378]
Okay @andrewxhill, tried to summarize what we chatted about:

- On the grid, 1px spacing looks neat, i think now we're 2px? (same for the thread 3, I guess margin as well?)
- On thread previews:
  - maybe even smaller thread title text
  - less margin-bottom on thread title (even 50% less)
  - date below, so that the title can use the full width, avoiding multi-lines being used
- On single photo feed items:
  - move date to bottom
  - put avatar next to name above photo, small and circle shaped
  - possibly use words to write out things like "peers" and "swarm", dunno 
  - use username text (not avatar) next to photo caption / comment

Some IG screenshots for reference:

![img_8089](https://user-images.githubusercontent.com/361000/44246103-3ff2b280-a191-11e8-8eaf-f96c102c83d3.PNG)

![img_8087](https://user-images.githubusercontent.com/361000/44241949-ea5fdb00-a17b-11e8-9883-dd9d1d6dd053.PNG)

**Comment by asutula** [comment]
These are done
