### ISSUE TITLE
Sticky thread rows

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#385]
Only ever seen this once... 

![img_8104](https://user-images.githubusercontent.com/361000/44355424-6b132580-a461-11e8-9bf7-688de6be2a58.PNG)

**Comment by sanderpick** [comment]
Oh, forgot to mention... when these originally got "stuck", I was still able to add photos direct from wallet.

**Comment by andrewxhill** [comment]
fixed with retry
