### ISSUE TITLE
Display and use location preference properly

### ISSUE THREAD

**Issue by asutula** [textileio/textile-mobile#408]
The preference for location should be respected separate of the OS status of location permission. This means, even if the OS permission is granted, if the user toggles off the location preference, we should stop monitoring location. 

Similarly, if the user has location preference toggled on, but has disabled access to location in the OS settings, we should display a message showing them that, ideally with a button to press that will open the OS location settings for our app so they can enable it.

**Comment by andrewxhill** [comment]
closable?

**Comment by asutula** [comment]
nope, still need to do it
