### ISSUE TITLE
Add comments

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-mobile#417]
Seems like we prob want to do right in the full stream view, so will need to do the expanding see all comment text etc, add in the comment authoring interface, blah blah

**Comment by sanderpick** [comment]
I assumed we'd turn on the single photo view again now that there's a use for it. So, when you tap on the comment bubble, it would take you to that view with the text input open. This would also let us navigate directly to the photo a notification is referencing... feels broken right now (obv. understandable, iterating, etc.) how it just takes you to the top of the feed... you don't know which photo was liked / commented on.

**Comment by andrewxhill** [comment]
yakpot
