### ISSUE TITLE
Is the site down?

### ISSUE THREAD

**Issue by kaushalmodi** [textileio/textile-mobile#418]
https://www.textile.photos/ gives me "Unable to connect" on Firefox.

**Comment by carsonfarmer** [comment]
Currently working for me...? Tested on Firefox, Safari, and Chrome. Can you give us additional information about your setup that might help us troubleshoot?

**Comment by kaushalmodi** [comment]
OK. I am closing this issue. Looks like, for whatever reason, the .photos domain is probably blocked at work.

I can access this site from my phone.
