### ISSUE TITLE
User registration stalled

### ISSUE THREAD

**Issue by fabianmu** [textileio/textile-mobile#424]
Endless spinner on the 2nd screen of a new user creation, I entered referral code, email, password and tapped the _create account_ button. 
[screenshot](https://www.dropbox.com/s/lieupapa61blqxz/IMG_4295.JPG?dl=0)

**Comment by asutula** [comment]
This was fixed by PR #420. If you installed from the app store, I believe the build with the fix (0.4.1) is waiting for review from Apple right now.

**Comment by andrewxhill** [comment]
@fabianmu the app should be available to update now, sorry!
