### ISSUE TITLE
Stalled when `adding To Wallet`

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-mobile#425]
After sitting for hours on 'adding To Wallet' in the add photo progress bar/indicator, an upload eventually became a blank white tile, and progress seems to have stalled permanently. See attached image for example.

![file](https://user-images.githubusercontent.com/1220613/44739812-af2fa700-aaad-11e8-8e6e-28f0e067f084.jpg)

**Comment by andrewxhill** [comment]
should be fixed
