### ISSUE TITLE
More seamless/ui-integrated on-boarding/messaging

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-mobile#437]
Since sometimes notifications don't come through right away (or at all?), should we have something more 'in your face' for thread invites and similar when actually 'in' the app? Currently, thread invites can be missed in the (long) list of photo likes, comments, adds, etc. Perhaps an in-app notification on any screen would be useful here?

**Comment by carsonfarmer** [comment]
We are using overlays in various places (empty threads list) to provide information and give feedback. It might be nice to pull this out into a more generic 'overlay' framework within the app, to make things like information, notifications, within the app easier to use?

**Comment by andrewxhill** [comment]
While counter intuitive, this is exactly opposite of the way that it's shown to work (see section starting page 34 https://www.dropbox.com/s/tuz2fj0qieiw1ov/Mobile%20Planet%2004182018.pdf?dl=0&utm_source=Benedict%27s+newsletter&utm_campaign=4f0e75adc0-Benedict%27s+Newsletter_COPY_01&utm_medium=email&utm_term=0_4999ca107f-4f0e75adc0-70802521). Especially slide 40, "I just want to get this out of my way"

It'd prefer to change this ticket to, More seamlessly/ui-integrated onboarding.

**Comment by andrewxhill** [comment]
closing in favor of new wireframes/outline
