### ISSUE TITLE
Keep track of 'past' peers

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-mobile#443]
Create thread, invite peer though external link, peer joins, you leave thread, ask peer to invite you back (using direct invite), you are no longer listed in their peer list. This is likely because they no longer have any shared threads with you. This might be an unexpected UX. We could consider keeping a table of all past peers? Rather than grabbing this from shared thread list?

**Comment by andrewxhill** [comment]
this is covered in a textile-go ticket,
https://github.com/textileio/textile-go/issues/178
