### ISSUE TITLE
UI Nits

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#450]
- [x] Tapping rows (contacts, notifications) makes the whole row go too transparent, a good deal less would feel nicer
- [x] A little bit more line spacing in the notification’s text would be sweet
- [x] IMO the thread titles in the threads list are still too big
- [x] it’s the total number in all threads i guess (15 on my sim now), but i’m looking at 5 photos in my wallet right below

**Comment by andrewxhill** [comment]
- [ ] failed upload UI cuts off for me

![img_7597](https://user-images.githubusercontent.com/370259/44927831-c7e8c880-ad0a-11e8-8328-10ab59f85d9e.PNG)

**Comment by sanderpick** [comment]
Re: Comments -
- [ ] Show last one or two comments in the feed below caption, with the count of not shown comments above
- [ ] Just show username next to comment, no avatar, at least for comments in the main feed
- [ ] Add comment bubble button (or similar?) next to heart in feed view... currently no way to know you could add a comment if you wanted to without going into the photo
- [ ] Should tapping the photo really link to the single view? Seems like if we had the comment button, that should be the only way to get to the single view
- [ ] Notifications about photos should link to the photo, not feed view

**Comment by sanderpick** [comment]
- [ ] Should be able to "like" from the single photo view

**Comment by andrewxhill** [comment]
- [ ] pinch zoom an image (seen it attempted by multiple users now)

**Comment by asutula** [comment]
Feel like we need to put some thought into the hierarchy of the thread/single image/comments UI. Feels like we're headed towards having no hierarchy and two screens that basically do the same thing. IG has put some thought into this and have a pretty subtle system of three screens: The feed view, the comments view, and a single image view that is a bit of a mix of the feed view and comments view. Seems like you only get to the single image view from the notifications screen.

**Comment by carsonfarmer** [comment]
I think this is related to #497.

**Comment by sanderpick** [comment]
Nice, sounds right.

**Comment by sanderpick** [comment]
- [ ] ﻿Placeholder text for feed view when empty (it's just blank white right now)

**Comment by asutula** [comment]
Moving each of these to individual issues now that we're going to spend some time focused on UX improvements. See https://github.com/textileio/textile-mobile/projects/1
