### ISSUE TITLE
Fix reloads in simulator

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#47]
While https://github.com/textileio/textile-mobile/pull/46 addresses node life cycle issues during the normal functioning of the app, it does not address the RN reload issue in the simulator. Thought I had fixed that, but no. The deal is that there's no "hook" to shutdown the node with (that i could find / know of)... and we seem to lose a reference to the existing go layer mobile node instance. So, a new one is created for each reload. You'll see some wonkiness in that the thumbs just show up white, but a lot more badness is happening under the hood.

**Comment by andrewxhill** [comment]
seems to work fine now! if someone else can confirm, we can close

**Comment by asutula** [comment]
Yea I notices this too. Maybe because we aren't running the gateway anymore?

**Comment by sanderpick** [comment]
yeah, think that's it. i did try reload again after not starting the gateway, but got some crash after a bunch of successive reloads so figured it was still an issue... but better than nothing!
