### ISSUE TITLE
Not able to register. Invalid character < Looking for start.

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-mobile#494]
Password (64 characters long) containing special characters leads to error on sign-up with: “Not able to register. Invalid character < Looking for start." error message. Removing all special characters seems to fix this, still with 64 characters.

**Comment by thorsten-panknin** [comment]
I'm sorry that the error message is probably not completely accurate. But interestingly, I did not have the character "<" in my first password. I checked for it.

**Comment by carsonfarmer** [comment]
Unable to reproduce so far on Android... @thorsten-panknin do you remember if the password used began with a special character or anything specific to help us reproduce?

**Comment by thorsten-panknin** [comment]
I'm sorry, but I don't have the initial password anymore and don't remember
what the first character was. It's possible it was a special character.

Carson Farmer <notifications@github.com> schrieb am Di., 18. Sep. 2018,
01:26:

**Comment by FernandoMiguel** [comment]
i got hit by this too.
i dont have '<' in the password, but it does have other special characters.
anyway, the input should be sanitised

**Comment by carsonfarmer** [comment]
This error is due to a timeout on the server-side from validating passwords (it times out on long passwords). Here's a 'fix' on the go side: https://github.com/textileio/textile-go/pull/298
This issue won't be relevant for much longer once we add profiles and no longer require passwords... so this is just a simple 'fix' until then.

**Comment by carsonfarmer** [comment]
The fix should be up and running later today.

**Comment by FernandoMiguel** [comment]
Yeah, random generated 60 characters long password

**Comment by sanderpick** [comment]
Thanks for the report, all... the fix is now running on our cafe nodes.

**Comment by FernandoMiguel** [comment]
Confirmed fixed.
Was able to register
