### ISSUE TITLE
Adding a photo to a thread from Textile itself doesn't carry over the description

### ISSUE THREAD

**Issue by thorsten-panknin** [textileio/textile-mobile#498]
Huawei P9 lite, Android 7, Textileversion 1.6.6

**Comment by asutula** [comment]
The app doesn't support adding captions to photos in the Textile wallet. If you share a photo from your camera roll or the Textile wallet to a thread with a comment, that comment is only associated with the share in that particular thread. The comment isn't added to the photo in the Textile wallet.
