### ISSUE TITLE
Fix RCTFatalException: Unhandled JS Exception: Invariant Violation: Objects are not valid as a React child (found: object with keys {domain, message, code}).

This error is located at:
    in RCTText
    in Text
    in RCTView
    in n
    in RCTView
    in e
    in RCTView
    in n
    in Connect(n)
    in t
    in RCTView
    in n
    in t
    in n
    in RCTView
    in RCTView
    in t
    in RCTView
    in e
    in r
    in Unknown
    in n
    in n
    in t
    in RCTView
    in n
    in t
    in n
    in RCTView
    in RCTView
    in t
    in RCTView
    in e
    in r
    in Unknown
    in n
    in n
    in t
    in t
    in withCachedChildNavigation(t)
    in Unknown
    in n
    in n
    in RCTView
    in t
    in Connect(t)
    in e
    in n
    in t
    in RCTView
    in RCTView
    in t in ReactNativeRenderer-prod.js line 2694

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-mobile#5]
### Reason ###

RCTFatalException: Unhandled JS Exception: Invariant Violation: Objects are not valid as a React child (found: object with keys {domain, message, code}).

This error is located at:
    in RCTText
    in Text
    in RCTView
    in n
    in RCTView
    in e
    in RCTView
    in n
    in Connect(n)
    in t
    in RCTView
    in n
    in t
    in n
    in RCTView
    in RCTView
    in t
    in RCTView
    in e
    in r
    in Unknown
    in n
    in n
    in t
    in RCTView
    in n
    in t
    in n
    in RCTView
    in RCTView
    in t
    in RCTView
    in e
    in r
    in Unknown
    in n
    in n
    in t
    in t
    in withCachedChildNavigation(t)
    in Unknown
    in n
    in n
    in RCTView
    in t
    in Connect(t)
    in e
    in n
    in t
    in RCTView
    in RCTView
    in t

### Link to App Center ###

* [https://appcenter.ms/users/andrewxhill/apps/Textile-Photos/crashes/groups/306da0fc4b1e15df53af5b88b723384b217a0620](https://appcenter.ms/users/andrewxhill/apps/Textile-Photos/crashes/groups/306da0fc4b1e15df53af5b88b723384b217a0620)

**Comment by asutula** [comment]
Think this just happened while I was developing, fixed it already

**Comment by andrewxhill** [comment]
Oh nice, this was an automated ticket from app center. Cool that it works. When we close the ticket too, it closes out the crash in AC i think.
