### ISSUE TITLE
Make Android builds available publicly (via releases or gx or ...)

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-mobile#525]
Some users report difficulty installing from Play Store, this would allow them to install the APK directly.

**Comment by sanderpick** [comment]
@asutula is this one done now via your recent tag release work? cc @letkan

**Comment by asutula** [comment]
I know we're archiving the apk on the CI server, but don't think we're pushing any build artifact to Github. Let's talk about the best way to do that.

**Comment by asutula** [comment]
Looks like the artifacts on CircleCI are not publicly visible. We'll have to change something there, or look at pushing artifacts to GH or elsewhere.

**Comment by sanderpick** [comment]
Cool, let's chat about it tomorrow morning. It's pretty simple if you can collect the artifacts from the other jobs. textile-go step: https://github.com/textileio/textile-go/blob/master/.circleci/config.yml#L491

**Comment by carsonfarmer** [comment]
https://gist.github.com/ralphpina/89ba0ebd942b487b53d187c0a808ff5e#file-ever-android-circleci-yml-L77

**Comment by andrewxhill** [comment]
closing this, they _should_ appear in the next GH android release
