### ISSUE TITLE
iPhone XS nits

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#548]
- [ ] "Next" button in bottom right corner during on-boarding is very hard to hit
- [ ] Back arrow covers "previous app" arrow in top left corner (see screenshot, ignore error)

![image from ios](https://user-images.githubusercontent.com/361000/45912983-65518c80-bddf-11e8-8b8e-eb131e27b417.png)

**Comment by asutula** [comment]
Done
