### ISSUE TITLE
V1.6.8 crashes on startup 

### ISSUE THREAD

**Issue by FernandoMiguel** [textileio/textile-mobile#559]
![screenshot_20180924-222441](https://user-images.githubusercontent.com/168366/45980091-042cf180-c049-11e8-961d-9654b3cd5ace.png)

Android P, pixel 2xl 

Instant crash on startup

**Comment by andrewxhill** [comment]
Hey @FernandoMiguel, we just pushed a 1.6.9, could you let us know if you still see the crash with that? Thanks

**Comment by FernandoMiguel** [comment]
1.6.9 works

**Comment by andrewxhill** [comment]
excellent, thanks for reporting
