### ISSUE TITLE
Overlay text being cut off on Android device

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-mobile#560]
Using a moto g 5 play, Android 7.1.1. Need to be more responsive for devices with different aspect ratios?
![sehicxyf](https://user-images.githubusercontent.com/1220613/45986382-1d6d7800-c020-11e8-92db-3a602898f92e.jpg)

**Comment by asutula** [comment]
Looking ok right now, but let's test on some devices.

**Comment by andrewxhill** [comment]
this should be fixed with the dynamic size i put in there
