### ISSUE TITLE
account gone

### ISSUE THREAD

**Issue by letkan** [textileio/textile-mobile#564]
Today I flashed a new rom on my device and logged into my Textile account but the pictures I uploaded yesterday were gone

**Comment by sanderpick** [comment]
The current "account" just represents the ability to remote pin your photos to our federated textile nodes. Your account "state" is currently _only local to your device_. @asutula @andrewxhill sounds like we need to be more clear about this in the app. I'm sure more users will expect to be able to login on a new device.

We're currently working on _full_ backup and recovery, which means the ability to login via a mnemonic phrase and recover your full account from the network in a decentralized manner. You can follow that project here: https://github.com/textileio/textile-go/projects. Thanks for the feedback!

**Comment by sanderpick** [comment]
I created a dedicated issue for this, https://github.com/textileio/textile-mobile/issues/569. Re: apks, that's indeed a priority: https://github.com/textileio/textile-mobile/issues/525

**Comment by letkan** [comment]
So today I recovered my previous rom on the phone and the original account was there, I found its files in /data/data/com.textile. I was wondering if it isn't simpler to backup that stuff in some form to storage and be able to restore it later if you change the rom. I don't know, maybe I'm oversimplifying.

**Comment by asutula** [comment]
Ok, I think it's clear we are working on recovery and APK/FDroid release. The relevant issues/projects have been referenced. Closing this issue.
