### ISSUE TITLE
Photos are getting cropped vertically on main feed

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-mobile#603]
Android (Samsung Note S8+). If this is referring to main Thread List view, then the vertical cropping is intentional... to conserve screen space and give equal 'weight' to each thread.

**Comment by doodlemania2** [comment]
Makes sense, however, we end up with stuff like this:

![image](https://user-images.githubusercontent.com/5252217/46704763-1c2c7580-cbf2-11e8-9125-8a68e1e3d98e.png)

instead of:
![20181007_170725](https://user-images.githubusercontent.com/5252217/46704772-264e7400-cbf2-11e8-912b-76e861cfcb71.jpg)

**Comment by carsonfarmer** [comment]
Ah no, this is an Android bug it seems. Cropping should only happen in your wallet and threadlist. Within a given thread, your photos should be uncropped.

**Comment by andrewxhill** [comment]
@doodlemania2 we're going to keep the unified ratio in the feed (so practically square), but now when you tap a photo you will get a full dimension, zoomable view

![1](https://user-images.githubusercontent.com/370259/55364760-c8129780-5496-11e9-9a6c-91886121d904.png)

![2](https://user-images.githubusercontent.com/370259/55364771-d06ad280-5496-11e9-8437-3d4bdc0ff3f0.png)

![3](https://user-images.githubusercontent.com/370259/55364777-d365c300-5496-11e9-8ddb-7f80e1f896a1.png)
