### ISSUE TITLE
Documentation for rolling your own

### ISSUE THREAD

**Issue by letkan** [textileio/textile-mobile#612]
Can you guys provide some documentation to help me build Android Textile, I'm no expert and don't use Google store (if I don't have to)? Thanks.

**Comment by andrewxhill** [comment]
hey @letkan, thanks for the push here. we've been meaning for ages to start pushing open builds of the apk for people to install. sooo... I just pushed that work, which means that the _next_ app release we do we will also build the install ready APK and it will be pushed right to github. Stay tuned, I'll ping you once that is out, I'm guessing tomorrow or Monday.

If you are super eager before we get the OS docs written up, you could dig into the android-release step in our CI https://github.com/textileio/textile-mobile/blob/master/.circleci/config.yml.

**Comment by andrewxhill** [comment]
here is the first apk btw https://github.com/textileio/textile-mobile/releases/tag/android_1.6.14_262

**Comment by letkan** [comment]
@andrewxhill, thanks for this. Meanwhile I messed up my account, any way to reset it? I could make a new one with a new username but would be nice to be able to reset it.

**Comment by asutula** [comment]
We're posting those APKs on Github release, which is what this issue was for, so closing.

@letkan, there is currently no way to "reset" an account.
