### ISSUE TITLE
Add cheap photo-exists lookup

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-mobile#650]
RN based key value store for original file hash (or if easy sha256) and the final Pin if it exists

**Comment by carsonfarmer** [comment]
Maybe useful:
https://www.npmjs.com/package/react-native-sha256

**Comment by andrewxhill** [comment]
cool, started to plot this out in my head and realized if we do it the cheap way (path existence) it could lead to a nasty edge case situation where the user shares the wrong photo.

1. `path/picA` comes in hash blah
2. months pass
3. a totally new `path/picA` comes in that happens to have the same path. we swap it out based on path name as key for the existing hash and share it

no good.

**Comment by asutula** [comment]
Sounds like we have a handle on this in the go layer. Closing.
