### ISSUE TITLE
Long usernames cut off on wallet view. 

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-mobile#702]
Screen capture from user reporting this issue: 
![9a85edc9-3d84-477f-9399-27760bd49834](https://user-images.githubusercontent.com/1220613/47955281-c9c14900-df52-11e8-9b55-b38ec6476966.jpeg)

**Comment by asutula** [comment]
Looks like they now just run off the right edge of the screen. Let's add some "..." handling to the truncation behavior.
