### ISSUE TITLE
Combine duplicate posts in the stream view 

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-mobile#703]
I thought this was a problem only I was having at this point, but just heard it from other people

Where, not the poster, but viewers are part of multiple feeds where you post a photo. 

E.g. I post a photo to both The Real Textile and Views from Work, each of you would see it twice. It'd be nice to have a way to collapse them into one post that when clicked or something expanded into the two captions... tricky but i'm sure a simple ux choice there

**Comment by asutula** [comment]
Sounds pretty tricky to create a good UX around that as long as threads are given they type of individual and important treatment we give them now. Would be easier if threads became more like the importance and use of 'tags'. For example, you can share a photo with a single caption and tag it to share in multiple threads. And that is an interesting idea.

**Comment by asutula** [comment]
I think this topic will be absorbed into larger discussions about UX and UI and product. Closing.
