### ISSUE TITLE
Recognize failed/errored image uploads and re-try them

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-mobile#74]
if the app crashes while (say) two images are uploading/waiting to upload, then there's never any saga to eventually go back and update those states or those upload pies. Part of the issue in the [upload library](https://github.com/textileio/react-native-background-upload) that we are using. It should really be fixed, or swapped for something more robust.

**Comment by carsonfarmer** [comment]
Related (or maybe in addition) to this, we need a way to update the image state when the upload/share _has_ completed, but the origin device doesn't know about it. See the attached image, which shows the shares were eventually successful, but the origin device hasn't updated its state yet.

**Comment by carsonfarmer** [comment]
<img width="572" alt="screen shot 2018-05-23 at 10 46 42 am" src="https://user-images.githubusercontent.com/1220613/40442131-b4ca1466-5e77-11e8-8226-cbc0fc3817b3.png">

**Comment by andrewxhill** [comment]
pretty odd, do you know what the failure is exactly? one thing here too, is that the shares viewer only ever uses thumbs, so maybe we could stop using full res at all there.

**Comment by carsonfarmer** [comment]
oh the failure was just an issue reaching our endpoint last night... probably due to poor internet connection. totally reasonable issue/failure. the point i was trying to make here is that it _did_ eventually complete, but the icons don't reflect this.
but yes, we could probs just add a flag to _not_ include the full res in the share uploads.

**Comment by carsonfarmer** [comment]
Oh yes Inguess that’s possible! I just assumed it did eventually complete (we could check this), but possible because they’re on the same network, that it was a p2p connection.
