### ISSUE TITLE
New group modal broken

### ISSUE THREAD

**Issue by asutula** [textileio/textile-mobile#791]
If you tap 'create group' from the wallet screen, the modal falls apart when the keyboard appears.

**Comment by andrewxhill** [comment]
Might need more info here. This is what I see,

![img_1932](https://user-images.githubusercontent.com/370259/51058004-4b110980-159c-11e9-943b-2491cc05232c.PNG)
![img_1933](https://user-images.githubusercontent.com/370259/51058005-4b110980-159c-11e9-8066-e974eac932db.PNG)

Is it a small screen issue?

**Comment by asutula** [comment]
Anyone looking at this yet @andrewxhill or @carsonfarmer?
