### ISSUE TITLE
Group contact previews don't auto update after JOIN

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#798]
**Describe the bug**
I have a contact, it joined a group via direct invite. However, the round avatars in the group list do not reflect this. After a hard kill, it looks correct, but clicking on the contact still saying "not part of any shared groups".

**To Reproduce**
1. Create a group
2. Direct invite a contact
3. View group list

**Expected behavior**
Avatar preview should auto-update.

**Smartphone (please complete the following information):**
 - Device: iPhone XS
 - OS: iOS 12.1.2
 - Version 6062

**Comment by andrewxhill** [comment]
Adding some info here.

These are coming from contacts redux now, which is built from node.contacts(). sounds like we need to wire up a call to just update that again on the onThreadUpdate block for any new joins.

**Comment by andrewxhill** [comment]
might be another thing at play here... display pending invites in a group's users. that is a different issue as it is going to take some tracking of that type, which we don't do now. 

opened this, https://github.com/textileio/textile-mobile/issues/800
