### ISSUE TITLE
Track and use pending group invites

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-mobile#800]
## Description
When you p2p invite a contact to a group, i think they are in a pending state until they accept. we should track/display those pending invites

## Initiative / goal
some redux state for pending contact invites to groups

### Hypothesis
success is a type of member avatar in a group's members that is 'pending'

**Comment by asutula** [comment]
This state management should be done in the go layer and the app can reflect that in the UI. See https://github.com/textileio/textile-go/issues/451

**Comment by asutula** [comment]
Slightly different use case there, it's talking about external invites, but I think the same logic applies for internal invites.
