### ISSUE TITLE
Add contact mockups

### ISSUE THREAD

**Issue by asutula** [textileio/textile-mobile#868]

**Comment by asutula** [comment]
![Screen Shot 2019-01-24 at 19.02.01.png](https://images.zenhubusercontent.com/5c23d3125bb3566961515697/eaf70094-a6d0-496b-8510-b8eac2aba460)

Thinking something like this for Add Contacts. This would pop up modally, and the search field would automatically have focus. To the right of the search field, you can toggle if you want to search Textile or your phone’s contacts or both simultaneously. The results are grouped by contact type. Tap a textile user, and i guess it’s simply added to your contacts. Tap a phone contact and it brings up the OS message composer to send a SMS/iMessage with a special link in it.

**Comment by sanderpick** [comment]
Dig it. I wonder if instead of the switch for textile / OS contacts, it just always did both and you can see some icon / text differentiator on each result row.

**Comment by asutula** [comment]
Could work. Only thought is that the queries of the two different data sources will take different amounts of time. Could be confusing if data from one source is displayed, you don't know if data from the second source is already displayed or not. And if not, then suddenly data from the second source pops in. Grouping the results like in the comp eliminates that confusion.

**Comment by asutula** [comment]
If we went with the grouped results, I'd imagine that while the data source is being queried, we'd display a table row in the corresponding section with a loading indicator.

**Comment by sanderpick** [comment]
Makes sense. I guess as a first pass, you could just _always_ search both and display the grouped results, vs. offering the toggle switches.

**Comment by asutula** [comment]
Totally. Sounds like a plan man.
