### ISSUE TITLE
Group screen mockup

### ISSUE THREAD

**Issue by asutula** [textileio/textile-mobile#869]

**Comment by asutula** [comment]
Working through ideas related to what I think will be the trickiest aspects of this screen: We support comments on photos, photos that have been posted sometime in the past, but we want to surface those comments in the feed as new information (at the head of the feed).

There are two main situations I can imagine:

1. Photo is shared, the next item(s) in the feed are comments on that photo
2. Photo is shared, some other item is shared (let's say a message), then a(some) comment(s) on the previously shared photo.

Here's what I'm thinking for #1 so far:
![Screen Shot 2019-02-07 at 12.30.06.png](https://images.zenhubusercontent.com/5c23d3125bb3566961515697/939f8e33-dc1a-424b-9f47-98a782ef7416)
In this case, the photo comments are appended onto the photo "card" and are presented as part of the shared photo's item.

For #2, we need to resurface some representation of the previously shared photo and display the newly added comments:
![Screen Shot 2019-02-07 at 12.30.23.png](https://images.zenhubusercontent.com/5c23d3125bb3566961515697/9e038a9f-e962-4678-b3c4-0b7574211535)
In this case, we display a thumbnail of the previously shared photo along with any new comments on the photo. Comments will be added to this "card" until there is a new feed item unrelated to the previously shared photo. If more comments come in later, we can repeat this photo comment card again in the feed.

**Comment by asutula** [comment]
Oh, in the photo comments card, there will be buttons to like and comment on the photo as well. I'm thinking they'll go right under the thumbnail.

**Comment by asutula** [comment]
The mechanics of simple chat items and photos are more simple. I guess there are some questions about how we want to support sharing/viewing multiple photos and how that impacts decisions about aspect ratio of images shared/viewed as a group.

**Comment by asutula** [comment]
One useful way to think about photo comments is kind of like "threads" in slack, where you can comment on a previous item, and optionally also display your comment at the head of the channel.

**Comment by sanderpick** [comment]
Love it. Will probably take some experimenting, but your slack analogy gives me confidence it could feel pretty natural. Only thought is for the "set" of photos... maybe the card is just the first one or maybe a collage or some kind. A tap could lead to a nice grid of them all where you can single tap each one, and then swipe though. Sounds more flex to me than the IG style of just swiping through them _within_ the feed. Because, as you say, we'd have to consider aspect ratios if we did it like that (as they do)

**Comment by sanderpick** [comment]
One of the screens I put in AT was around the idea of seeing all the group's photos in a grid from the group info screen, "Group Photos" screen. This could help make the group space feel more photo-centric, as apposed to generic chat.

**Comment by sanderpick** [comment]
So like, maybe there's an "info" button in the upper-right corner of a group view. Tap that, and inside there's a row button to view all Photos or something... an enhancement for sure

**Comment by sanderpick** [comment]
and another row button to view all Members

**Comment by asutula** [comment]
Cool, thanks for your thoughts. That all sounds reasonable. Think I'll start with the simple feed of messages, photos, and photo comments, then we can enhance with photo grids and group info screen etc
