### ISSUE TITLE
Skipping referral code entry on-boarding screen

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-mobile#893]
**Describe the bug**
During on-boarding on some Android devices, the referral code screen is flashed and skipped

**To Reproduce**
1. Install app from Play Store
2. Run through on-boarding sequence
3. Get to 3rd screen, see flash of referral code screen, skip past
4. No forward arrow button left, this is the error

**Expected behavior**
Should not skip code entry screen, and should not side forward arrow button

**Screenshots**
![tmp_test](https://user-images.githubusercontent.com/1220613/52151920-847fe680-2629-11e9-8c21-113e221aae4a.gif)

**Smartphone (please complete the following information):**
 - Device: Android (Essential PH-1, Xiaomi Redmi 5 Plus, etc)
 - OS: Android Oreo 8.1,e tc
 - Version 0.5.{2,3}

**Additional context**
This has been reported by several Android users now

**Comment by PoorPocketsMcNewHold** [comment]
I can confirm that #894 did fixed that issue for me.

**Comment by PoorPocketsMcNewHold** [comment]
So, #984 did fixed that issue for me in a weird way... It not skip it only on paysage mode, but it does still skip it on portrait mode like previously showed. I will upload a preview later.

**Comment by carsonfarmer** [comment]
Super helpful thanks @PoorPocketsMcNewHold! This should help us narrow down the issue 👍.

**Comment by carsonfarmer** [comment]
Confirmed report on Xiaomi Redmi 5 Plus with Android Oreo 8.1.
