### ISSUE TITLE
Photos cut off on Android

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-mobile#895]
**Describe the bug**
Depending on orientation of device, some photos are being cut off from display on Android devices. This seems to be a scaling/fit to screen issue, as the 'raw' photos themselves are fine.

**To Reproduce**
1. Take a portrait photo on device or in app
2. Share to a group
3. View shared photo in group feed
4. Depending on orientation of photo and device, heads are cropped, or scenes are cut-out

**Expected behavior**
Images should be resized to fit the available view screen

**Screenshots**
None-available yet...

**Smartphone (please complete the following information):**
 - Device: Android, all
 - OS: All
 - Version 1.0.0-rc31 (and likely previous versions)

**Additional context**
This bug has appeared in the past, but the source was not found.

**Comment by carsonfarmer** [comment]
Related to/duplicate of: #603.

**Comment by andrewxhill** [comment]
this may come back up when we remove the square frame, but killing for now
