### ISSUE TITLE
Discontinue peerswap requests from migration

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-mobile#963]
Seems like this has been going long enough, we should stop these checks and rest of that code probably.

**Comment by asutula** [comment]
Ah cool. I already removed the rest of the migration code and must have just forgot this.

**Comment by andrewxhill** [comment]
i don't see any migration related code left. _there are_ migration functions in the RN sdk, so moving this ticket over there

**Comment by andrewxhill** [comment]
Issue moved to [textileio/react-native-sdk #72](https://github.com/textileio/react-native-sdk/issues/72) via [**ZenHub**](https://www.zenhub.com/)
