### ISSUE TITLE
No need to show my avatar the second time

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-mobile#964]
![IMG_F0637D0875C1-1.jpeg](https://images.zenhubusercontent.com/5c2e63724feb4829c0135244/47b8f5e7-88dc-42f0-bd44-85a851325bff)

**Comment by asutula** [comment]
Yea totally. We're going to switch the feed to "stack" mode, and we should make sure we have a stack type for messages from the same user within some amount of time. Idea would be that if i send consecutive messages with less than a minute in between, they should be grouped into a single stack. What do you think of that @sanderpick? If it seems like the right idea, we can track an issue in go-textile.

**Comment by sanderpick** [comment]
Ah yeah, good call!

**Comment by andrewxhill** [comment]
fixed here https://github.com/textileio/textile-mobile/pull/985
