### ISSUE TITLE
Ensure that photos taking 'in app' don't end up in default camera roll

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-mobile#968]
This is already the default on iOS, and _should_ also be the default on Android. If a photo is taken 'in app', it should _not_ be available outside of the Textile Photos app. This is in line with behavior on iOS, and with other, similarly privacy-focused, apps.

Here's a link to the native image picker API for React Native:
https://github.com/react-native-community/react-native-image-picker/blob/master/docs/Reference.md#options

**Comment by andrewxhill** [comment]
duplicate https://app.zenhub.com/workspaces/-textile-5c2d497b5bb3566961516d2a/issues/textileio/textile-mobile/962
