### ISSUE TITLE
Android: stuck on 'pick a display name'

### ISSUE THREAD

**Issue by carsonfarmer** [textileio/textile-mobile#973]
Problem: During on-boarding, user was able to "pick display name," put one it, get a success manager, but the screen doesn't advance. It flashes to "get started" for a second before reverting back to the "pick a display name" screen.

Device, OS: OnePlus 3, Android v8

Context: Issue reported by new user via Twitter

**Comment by andrewxhill** [comment]
fixed and released

https://github.com/textileio/textile-mobile/pull/978

https://github.com/textileio/textile-mobile/releases/tag/android_0.5.8_279
