### ISSUE TITLE
Streaming contact results need to be de-duped

### ISSUE THREAD

**Issue by andrewxhill** [textileio/textile-mobile#974]
Streaming search results may return newer copies of contact info for an already returned peer. Apps will need to filter results (or replace display of a result with new info) as they come in.

![IMG_2447](https://user-images.githubusercontent.com/370259/54848466-8b78bc00-4c9e-11e9-9b36-3339492355c3.JPG)

**Comment by asutula** [comment]
There's a chance there is also an additional duplicate result because of the same result coming back as `local` and another not local.

**Comment by sanderpick** [comment]
Have you seen that happen @asutula?

**Comment by asutula** [comment]
I think so, but would have to confirm. If you search for a contact you already have added, it makes sense that that would happen, right?

**Comment by sanderpick** [comment]
I'll have to double check the logic... I _think_ it should always show as local if you have a local copy. But, doing the row replace as results arrive, so that each row is unique by ID, would be a good place to start.
