### ISSUE TITLE
Group screen bounce weirdness

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#975]
Android only. The only way to scroll the view is to press is slide your finger. It's a little hard to explain but you cannot "swipe" up or down because it will act as if it's bouncing off a wall that doesn't exist... in other words, it "bounces" back to where you swiped from.

**Comment by andrewxhill** [comment]
fixed: https://github.com/textileio/textile-mobile/pull/982 
but leads to needing, https://github.com/textileio/textile-mobile/pull/983
