### ISSUE TITLE
Photos overflow in feed

### ISSUE THREAD

**Issue by sanderpick** [textileio/textile-mobile#976]
Android only. 

![Screenshot 2019-03-24 09.47.49.png](https://images.zenhubusercontent.com/5c2e879a4feb4829c013530c/2b3e1f66-b738-4ed1-91b9-2c8aacf1ab8d)

**Comment by andrewxhill** [comment]
fixed for now by just cropping same as ios https://github.com/textileio/textile-mobile/pull/980
